### ISSUE TITLE
🐛 [ Bug ]: 没法一键闯关了

### ISSUE THREAD

**Issue by cj841192685** [LauZzL/ltzj-nem#123]
#### 您使用的版本？
3.2.4

#### 系统版本？
win11

#### 您遇到了什么问题？
现在用这个工具没法一键闯关了，望尽快更新

#### 请提供错误截图？
![img_v3_02gh_20abb9a2-d080-473a-80cf-6b1eab02502g](https://github.com/user-attachments/assets/7324febf-0bcd-45a4-89ce-94bcec887c82)

**Comment by xiaoyanguu** [comment]
我也是，好像是昨天下午不可以的，早上还可以

**Comment by brbr194** [comment]
我也是，无尽，boss，闯关都不行了，都是提示亲爱的玩家，不要修改不要作弊不要蒙混过关哦，梦想不能有折扣

**Comment by ZhiKangMai** [comment]
我也是，不能用了

**Comment by 1821920744** [comment]
没有这个辅助，我已经一周没玩了

**Comment by 2503272265** [comment]
作者都没声没响了

**Comment by 1821920744** [comment]
每日一问

**Comment by YUETWER** [comment]
作者停更一个月 让倒卖🐕着急去吧

**Comment by Ayy321SSS** [comment]
![7b0bdc5acdee6c3263f0c7fea943d2a](https://github.com/user-attachments/assets/4b11270c-b148-4e37-a6e2-2ed2f3eeaa5c)


> 已经修复了 但是，由于倒卖代打太多了 暂时不会发布新版本的哈

**Comment by 2503272265** [comment]
> 已经修复了 但是，由于倒卖代打太多了 暂时不会发布新版本的哈

用不了哎

**Comment by 853097424** [comment]
> @1821920744 @2503272265 @BNM520 已经修复了 但是由于倒卖代打太多了 暂时不会发布新版本的哈

用不了呀，能不能私发一份

**Comment by Mars039** [comment]
请问大佬, 我只会简单的 vue2, vue3 , 不懂nodejs, 可以自己修改吗, 没头绪呢

**Comment by cj841192685** [comment]
> @1821920744 @2503272265 @BNM520 已经修复了 但是由于倒卖代打太多了 暂时不会发布新版本的哈

其实就应该这样，不应该让别人拿着自己的成果去赚钱

**Comment by BNM520** [comment]
倒勾真盖斯啊

**Comment by 2503272265** [comment]
倒狗真恶心

**Comment by qqb-007** [comment]
大佬，我自用，能私发一份吗？非常感谢 @LauZzL

**Comment by cj841192685** [comment]
> 大佬，我自用，能私发一份吗？非常感谢 @LauZzL

着啥急，越着急，越感觉你是倒卖的，看作者心情，他想啥时候发就啥时候发

**Comment by qqb-007** [comment]
> > 大佬，我自用，能私发一份吗？非常感谢 @LauZzL
> 
> 着啥急，越着急，越感觉你是倒卖的，看作者心情，他想啥时候发就啥时候发

哈哈  主要是扫荡卡快用光了

**Comment by 2503272265** [comment]
> > > 大佬，我自用，能私发一份吗？非常感谢 @LauZzL
> > 
> > 
> > 着啥急，越着急，越感觉你是倒卖的，看作者心情，他想啥时候发就啥时候发
> 
> 哈哈 主要是扫荡卡快用光了

没有了就不玩呗，这又不是上班，天天得玩

**Comment by 1821920744** [comment]
为什么会抄送给我




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LauZzL/leitingzhanji-ui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月19日(星期二) 中午11:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LauZzL/leitingzhanji-ui] 🐛 [ Bug ]: 没法一键闯关了 (Issue #123)





    
大佬，我自用，能私发一份吗？非常感谢 @LauZzL
  
着啥急，越着急，越感觉你是倒卖的，看作者心情，他想啥时候发就啥时候发
  
哈哈 主要是扫荡卡快用光了
  
没有了就不玩呗，这又不是上班，天天得玩

**Comment by 1821920744** [comment]
更新啦

**Comment by yellow255** [comment]
> @1821920744 @2503272265 @BNM520已经修复了但是倒卖代打太多了由于暂时不会发布新版本的哈

大佬能不能私发一份😭

**Comment by cj841192685** [comment]
> 更新啦

更新个锤子，我还以为可以下载最新版本了

**Comment by yellow255** [comment]
> @1821920744 @2503272265 @BNM520已经修复了但是倒卖代打太多了因为暂时不会发布新版本的哈

大佬能私发一份嘛

**Comment by cj841192685** [comment]
@LauZzL 可以单独发我一份吗

**Comment by 853097424** [comment]
> 更新啦

我还以为更新了

**Comment by yiXaoXue** [comment]
> @1821920744 @2503272265 @BNM520 已经修复了 但是由于倒卖代打太多了 暂时不会发布新版本的哈

劳斯 私发我一下  我买

**Comment by 1821920744** [comment]
大更新，新版本一起上啦

**Comment by yiXaoXue** [comment]
@1821920744 劳斯 可以发我吗 我买

**Comment by Ly9751** [comment]
@LauZzL 哥能私发给我吗，已经一个星期没完了。

**Comment by BNM520** [comment]
新版本了 再卡几天 让倒勾再急几天

**Comment by Mars039** [comment]
不要急,  等待~~~, 至少现在 星际探索,  商城礼包,  免费体力, 这三个东西, 不用看广告, 不看广告我就很满足了

**Comment by texiwustion** [comment]
> @1821920744 @2503272265 @BNM520 已经修复了 但是由于倒卖代打太多了 暂时不会发布新版本的哈

可以分享boss关的封包/修复思路吗

**Comment by 1821920744** [comment]
每日一修

**Comment by 1821920744** [comment]
最新版本，大更新啦

**Comment by 1821920744** [comment]
latest

**Comment by Mars039** [comment]
如果  把登入的账户 和 本机MAC地址绑定, 做验证, 是不是就只能, 限制一台设备 只有一个账户能使用?
