### ISSUE TITLE
🐛 [ Bug ]: 无法获取到sid或uid

### ISSUE THREAD

**Issue by 853097424** [LauZzL/ltzj-nem#131]
#### 您使用的版本？
3.2.5

#### 系统版本？
win11

#### 您遇到了什么问题？
无法获取到sid或uid，显示环境异常，重启，换号，重新下载安装，都没有用

#### 请提供错误截图？
![1732709811826](https://github.com/user-attachments/assets/285ab3ac-5c1e-4d6e-bd7e-5cbaf3ecd564)

**Comment by ASCIIX** [comment]
疑似仅登录一个账号，拒绝盗版。

**Comment by 853097424** [comment]
> 疑似仅登录一个账号，拒绝盗版。

测试，大概率是只能一机一号，防倒狗毫无意义，能用还是照样二次倒卖，

**Comment by 1821920744** [comment]
> 疑似仅登录一个账号，拒绝盗版。

大佬，这个辅助是怎么个流程。抓包获取的接口，然后构造的请求吗？

**Comment by Mars039** [comment]
就是只能  一台设备只能辅助一个游戏账号,  这个不是bug, 是故意设计成这样的,

**Comment by feng7V5** [comment]
更新也没说明,现在好了,大号不能用了,也只能弃坑了

**Comment by YUETWER** [comment]
我也是先登的小号 限度可不可开放一些呀？ 比如一个电脑最多绑定三个UID 不然多号的好难受啊 主要是一键广告不能再用了

**Comment by LauZzL** [comment]
环境异常是RC版本授权用户留下来的废案 忘记删除了 24小时内会恢复 隔一段时间重试一下就行了

**Comment by feng7V5** [comment]
可以了上了,感谢大佬
