### ISSUE TITLE
🐛 [ Bug ]: 

### ISSUE THREAD

**Issue by zephyrus-ux** [LauZzL/ltzj-nem#132]
#### 您遇到了什么问题？初始化后登录游戏显示请不要修改数据哦，uid始终无法获取
![0cd3738c-bc17-4a2e-a13a-3fa3fdc1c030](https://github.com/user-attachments/assets/935b82d2-a58f-472a-8cb5-d36be409ce0d)

**Comment by zephyrus-ux** [comment]
您好，我并没有登录别的账号，他登录后直接提示请不要修改数据，uid就根本登不上




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月27日(星期三) 晚上11:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LauZzL/ltzj-nem] 🐛 [ Bug ]:  (Issue #132)














 
uid 无法获取, 是因为 现在 一台电脑上 只能 给一个账号辅助, 想给小号辅助 是不可以的

**Comment by feng7V5** [comment]
![image](https://github.com/user-attachments/assets/e4c887fc-1465-4883-96bc-9ff314a383b7)
不小心登入了小号,现在大号不能上了,怎么解决啊,急急急

**Comment by LauZzL** [comment]
网络原因 更换网络环境重试
