### ISSUE TITLE
🐛 [ Bug ]: 活动关卡更新后不能一键完成

### ISSUE THREAD

**Issue by TIMshao668** [LauZzL/ltzj-nem#133]
#### 您使用的版本？
3.2.5

#### 系统版本？
Windows11

#### 您遇到了什么问题？
活动关卡更新后不能一键完成

#### 请提供错误截图？
![b366c337-49b1-40b5-8ea9-a07dd7e2a586](https://github.com/user-attachments/assets/f2fe81b8-bf01-4670-bf3a-9d6361bfc273)

**Comment by 1821920744** [comment]
+1

**Comment by 1821920744** [comment]
为什么现在自定义关卡会等待很久了

**Comment by 1821920744** [comment]
为什么现在自定义关卡会等待很久了

**Comment by TIMshao668** [comment]
因为作者加了时延，用来适配游戏反作弊因为通关时间过短导致的检测，不过好像时延加多少也还是会被检测到

**Comment by 1821920744** [comment]
> 因为作者加了时延，用来适配游戏反作弊因为通关时间过短导致的检测，不过好像时延加多少也还是会被检测到

新出的关卡打不了

**Comment by TIMshao668** [comment]
那得跟作者反映，毕竟加了反作弊，现在只能打已经打过的关卡
