### ISSUE TITLE
🐛 [ Bug ]: 新版本闯关依旧有些问题

### ISSUE THREAD

**Issue by JXNS-GUO** [LauZzL/ltzj-nem#135]
#### 您使用的版本？
3.2.6

#### 系统版本？
win11

#### 您遇到了什么问题？
新版本闯关自定义模式打英雄模式，第一关可以正常通过，后续关卡还是会弹梦想不能打折

#### 请提供错误截图？

![Uploading bug.png…]()

**Comment by JXNS-GUO** [comment]
![bug](https://github.com/user-attachments/assets/1fdb820e-5c3b-447f-974d-2a3108080458)

**Comment by LauZzL** [comment]
无法复现

**Comment by JXNS-GUO** [comment]
大佬没太搞懂无法复现是啥意思😂



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月2日(周一) 下午4:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [LauZzL/ltzj-nem] 🐛 [ Bug ]: 新版本闯关依旧有些问题 (Issue #135)




 
无法复现

**Comment by LauZzL** [comment]
@JXNS-GUO  https://www.baidu.com/s?wd=%E6%97%A0%E6%B3%95%E5%A4%8D%E7%8E%B0
