### ISSUE TITLE
🐛 [ Bug ]: 自定义闯关模式失败

### ISSUE THREAD

**Issue by JXNS-GUO** [LauZzL/ltzj-nem#137]
#### 您使用的版本？

3.2.7

#### 系统版本？

win11

#### 您遇到了什么问题？

英雄模式和普通82关还是会弹不要作弊，但是90关正常，有些关卡还是有问题

#### 请提供错误截图？
![普通82](https://github.com/user-attachments/assets/1e0e7851-d137-4fe5-8a34-c8cf5d983417)
![英雄2](https://github.com/user-attachments/assets/79a61664-fb2f-48e8-8955-e1042f3744b6)

**Comment by LauZzL** [comment]
调整timer 希望你认真看更新日志或通告
