### ISSUE TITLE
🤔 [ Question ]: 新版本小程序使用3.27会导致封号

### ISSUE THREAD

**Issue by charlotte-cpu** [LauZzL/ltzj-nem#141]
### 系统版本
1.3.5

### 程序版本
3.2.7

### 截图 (如果可以)
![屏幕截图 2024-12-06 165800](https://github.com/user-attachments/assets/7d4582ea-5ce7-41a2-9842-897317bd7436)

**Comment by LauZzL** [comment]
...

**Comment by TIMshao668** [comment]
这个不是封号，是系统显示的bug，今天已被更新修复
