### ISSUE TITLE
🤔 [ Question ]: 修改分数后攻打失败

### ISSUE THREAD

**Issue by ukpkmkkkum** [LauZzL/ltzj-nem#145]
### 系统版本
Windows11

### 程序版本
3.3.1

### 详细描述你的问题
已换低等级装备，并将Timer调整至100，修改分数后攻打失败

### 截图 (如果可以)
<img width="621" alt="aa8006828a8f1a726847f65d26ea3b7" src="https://github.com/user-attachments/assets/7e0cb311-c5aa-40d8-a259-a7ad2d09a33c" />
<img width="676" alt="37d621de41fb9ed4b27590e4dcb1950" src="https://github.com/user-attachments/assets/e8069824-1f7c-4591-ad2a-46d603787c54" />

**Comment by Mofan1379** [comment]
你别改不就得了

**Comment by ukpkmkkkum** [comment]
所以这个功能无法使用？

**Comment by ukpkmkkkum** [comment]
> 你别改不就得了

所以这个功能是无法使用的？

**Comment by LauZzL** [comment]
由于游戏反作弊机制 所以分数过大无法结算
