### ISSUE TITLE
🐛 [ Bug ]: 爱乐游更新了，获取不到账号信息了

### ISSUE THREAD

**Issue by JXNS-GUO** [LauZzL/ltzj-nem#148]
#### 您使用的版本？

3.3.1
#### 系统版本？

win11
#### 您遇到了什么问题？

爱乐游更新了，获取不到账号信息了，全部功能失效
#### 请提供错误截图？
![{8C4F3FFB-DE44-457D-95EB-3CA7C34B8CF6}](https://github.com/user-attachments/assets/ccf01ba1-7664-4b99-aeeb-16305c750e33)

**Comment by LauZzL** [comment]
在刀锋版本前上线

**Comment by 1821920744** [comment]
![image](https://github.com/user-attachments/assets/c3eb28db-6552-4285-b311-c0b819b6a1a7)

**Comment by 1821920744** [comment]
用不了了
