### ISSUE TITLE
🤔 [ Question ]: 已经知道官方会更新关于反作弊的东西了，看看能搞多少就弄多少吧

### ISSUE THREAD

**Issue by TIMshao668** [LauZzL/ltzj-nem#149]
### 系统版本

Win11
### 程序版本

3.3.2
### 详细描述你的问题
如题所示

### 截图 (如果可以)

![57E02C6D8D423F7E3201E57872967E37](https://github.com/user-attachments/assets/1d42f8a1-b62f-442a-ae91-deac09eb8ccd)

**Comment by 1821920744** [comment]
用不了了
