### ISSUE TITLE
🐛 [ Bug ]: 

### ISSUE THREAD

**Issue by qianyezzyyy** [LauZzL/ltzj-nem#151]
#### 您使用的版本？
3.3.3

#### 系统版本？
win11
#### 您遇到了什么问题？
无法自动安装证书，初始化提示乱码

#### 请提供错误截图？
![image](https://github.com/user-attachments/assets/1e2ac29a-f3f5-4797-abc4-9b08de2a104f)
![image](https://github.com/user-attachments/assets/b540aa23-c307-42a5-b857-f0c0eb00ef99)

**Comment by LauZzL** [comment]
#19

**Comment by qianyezzyyy** [comment]
> #19

搞定了。感谢
